export const images = {
    logo: require("./public/images/logo.png"),
    homePage_image: require("./public/images/homePage_image.jpg"),
    Import_Of_Steel_Products: require("./public/images/Import_Of_Steel_Products.jpg"),
    Private_Construction: require("./public/images/Private_Construction.jpg"),
    Industrial_Construction: require("./public/images/Industrial_Construction.jpg"),
    Aclimatic_images: [
        require("./public/images/Aclimatic1.jpg"),
        require("./public/images/Aclimatic2.jpg"),
        require("./public/images/Aclimatic3.jpg"),
        require("./public/images/Aclimatic4.jpg"),
        require("./public/images/Aclimatic5.jpg"),
        require("./public/images/Aclimatic6.jpg"),
    ],
    Fotter_image : require("./public/images/Fotter_image.jpeg"),
    Industrial_Construction_image: require("./public/images/Industrial_Construction.jpg"),
    Private_Construction_image: require("./public/images/Private_Construction.jpg"),
    Import_Of_Steel_Products_image: require("./public/images/Import_Of_Steel_Products.jpg"),
    Advanced_construction_image: require("./public/images/Advanced_construction.jpg"),
    x_icon: require("./public/images/x_icon.png"),
    Hamburger_icon: require("./public/images/Hamburger_icon.png"),
    facebook_icon: require("./public/images/facebook_icon.png"),
    gmail_icon: require("./public/images/Gmail_icon.png"),

}